FROM nginx:alpine

COPY --chown=nginx:nginx ./_site /usr/share/nginx/html/guide

RUN mkdir -p /var/cache/nginx

RUN chown -R nginx:nginx /var/cache/nginx
RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid

USER nginx

WORKDIR /usr/share/nginx/html
