FROM node:20.5-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./

RUN npm install
COPY . .
RUN npm run build


FROM nginx:alpine AS final

COPY --from=builder /app/_site/ /usr/share/nginx/html/guide
